-- Project iFacture
-- ---------------------------------------------------------------------------
-- SQL Script to add pays
-- ---------------------------------------------------------------------------
-- COMMANDS IN THIS SCRIPT SHOULD BE EXECUTED WITH SUPERUSER
-- psql -U postgres -d db_ifacture -a -f pays.sql
-- ---------------------------------------------------------------------------

INSERT INTO ifacture.t_pays VALUES ('AF','Afghanistan');
INSERT INTO ifacture.t_pays VALUES ('ZA','Afrique du Sud');
INSERT INTO ifacture.t_pays VALUES ('AL','Albanie');
INSERT INTO ifacture.t_pays VALUES ('DZ','Algérie');
INSERT INTO ifacture.t_pays VALUES ('DE','Allemagne');
INSERT INTO ifacture.t_pays VALUES ('AD','Andorre');
INSERT INTO ifacture.t_pays VALUES ('AO','Angola');
INSERT INTO ifacture.t_pays VALUES ('AI','Anguilla');
INSERT INTO ifacture.t_pays VALUES ('AQ','Antarctique');
INSERT INTO ifacture.t_pays VALUES ('AG','Antigua-et-Barbuda');
INSERT INTO ifacture.t_pays VALUES ('AN','Antilles néerlandaises');
INSERT INTO ifacture.t_pays VALUES ('SA','Arabie saoudite');
INSERT INTO ifacture.t_pays VALUES ('AR','Argentine');
INSERT INTO ifacture.t_pays VALUES ('AM','Arménie');
INSERT INTO ifacture.t_pays VALUES ('AW','Aruba');
INSERT INTO ifacture.t_pays VALUES ('AU','Australie');
INSERT INTO ifacture.t_pays VALUES ('AT','Autriche');
INSERT INTO ifacture.t_pays VALUES ('AZ','Azerbaïdjan');
INSERT INTO ifacture.t_pays VALUES ('BS','Bahamas');
INSERT INTO ifacture.t_pays VALUES ('BH','Bahreïn');
INSERT INTO ifacture.t_pays VALUES ('BD','Bangladesh');
INSERT INTO ifacture.t_pays VALUES ('BB','Barbade');
INSERT INTO ifacture.t_pays VALUES ('PW','Belau');
INSERT INTO ifacture.t_pays VALUES ('BE','Belgique');
INSERT INTO ifacture.t_pays VALUES ('BZ','Belize');
INSERT INTO ifacture.t_pays VALUES ('BJ','Bénin');
INSERT INTO ifacture.t_pays VALUES ('BM','Bermudes');
INSERT INTO ifacture.t_pays VALUES ('BT','Bhoutan');
INSERT INTO ifacture.t_pays VALUES ('BY','Biélorussie');
INSERT INTO ifacture.t_pays VALUES ('MM','Birmanie');
INSERT INTO ifacture.t_pays VALUES ('BO','Bolivie');
INSERT INTO ifacture.t_pays VALUES ('BA','Bosnie-Herzégovine');
INSERT INTO ifacture.t_pays VALUES ('BW','Botswana');
INSERT INTO ifacture.t_pays VALUES ('BR','Brésil');
INSERT INTO ifacture.t_pays VALUES ('BN','Brunei');
INSERT INTO ifacture.t_pays VALUES ('BG','Bulgarie');
INSERT INTO ifacture.t_pays VALUES ('BF','Burkina Faso');
INSERT INTO ifacture.t_pays VALUES ('BI','Burundi');
INSERT INTO ifacture.t_pays VALUES ('KH','Cambodge');
INSERT INTO ifacture.t_pays VALUES ('CM','Cameroun');
INSERT INTO ifacture.t_pays VALUES ('CA','Canada');
INSERT INTO ifacture.t_pays VALUES ('CV','Cap-Vert');
INSERT INTO ifacture.t_pays VALUES ('CL','Chili');
INSERT INTO ifacture.t_pays VALUES ('CN','Chine');
INSERT INTO ifacture.t_pays VALUES ('CY','Chypre');
INSERT INTO ifacture.t_pays VALUES ('CO','Colombie');
INSERT INTO ifacture.t_pays VALUES ('KM','Comores');
INSERT INTO ifacture.t_pays VALUES ('CG','Congo');
INSERT INTO ifacture.t_pays VALUES ('KP','Corée du Nord');
INSERT INTO ifacture.t_pays VALUES ('KR','Corée du Sud');
INSERT INTO ifacture.t_pays VALUES ('CR','Costa Rica');
INSERT INTO ifacture.t_pays VALUES ('CI','Côte d''Ivoire');
INSERT INTO ifacture.t_pays VALUES ('HR','Croatie');
INSERT INTO ifacture.t_pays VALUES ('CU','Cuba');
INSERT INTO ifacture.t_pays VALUES ('DK','Danemark');
INSERT INTO ifacture.t_pays VALUES ('DJ','Djibouti');
INSERT INTO ifacture.t_pays VALUES ('DM','Dominique');
INSERT INTO ifacture.t_pays VALUES ('EG','Égypte');
INSERT INTO ifacture.t_pays VALUES ('AE','Émirats arabes unis');
INSERT INTO ifacture.t_pays VALUES ('EC','Équateur');
INSERT INTO ifacture.t_pays VALUES ('ER','Érythrée');
INSERT INTO ifacture.t_pays VALUES ('ES','Espagne');
INSERT INTO ifacture.t_pays VALUES ('EE','Estonie');
INSERT INTO ifacture.t_pays VALUES ('US','États-Unis');
INSERT INTO ifacture.t_pays VALUES ('ET','Éthiopie');
INSERT INTO ifacture.t_pays VALUES ('MK','ex-République yougoslave de Macédoine');
INSERT INTO ifacture.t_pays VALUES ('FI','Finlande');
INSERT INTO ifacture.t_pays VALUES ('FR','France');
INSERT INTO ifacture.t_pays VALUES ('GA','Gabon');
INSERT INTO ifacture.t_pays VALUES ('GM','Gambie');
INSERT INTO ifacture.t_pays VALUES ('GE','Géorgie');
INSERT INTO ifacture.t_pays VALUES ('GH','Ghana');
INSERT INTO ifacture.t_pays VALUES ('GI','Gibraltar');
INSERT INTO ifacture.t_pays VALUES ('GR','Grèce');
INSERT INTO ifacture.t_pays VALUES ('GD','Grenade');
INSERT INTO ifacture.t_pays VALUES ('GL','Groenland');
INSERT INTO ifacture.t_pays VALUES ('GP','Guadeloupe');
INSERT INTO ifacture.t_pays VALUES ('GU','Guam');
INSERT INTO ifacture.t_pays VALUES ('GT','Guatemala');
INSERT INTO ifacture.t_pays VALUES ('GN','Guinée');
INSERT INTO ifacture.t_pays VALUES ('GQ','Guinée équatoriale');
INSERT INTO ifacture.t_pays VALUES ('GW','Guinée-Bissao');
INSERT INTO ifacture.t_pays VALUES ('GY','Guyana');
INSERT INTO ifacture.t_pays VALUES ('GF','Guyane française');
INSERT INTO ifacture.t_pays VALUES ('HT','Haïti');
INSERT INTO ifacture.t_pays VALUES ('HN','Honduras');
INSERT INTO ifacture.t_pays VALUES ('HK','Hong Kong');
INSERT INTO ifacture.t_pays VALUES ('HU','Hongrie');
INSERT INTO ifacture.t_pays VALUES ('BV','Ile Bouvet');
INSERT INTO ifacture.t_pays VALUES ('CX','Ile Christmas');
INSERT INTO ifacture.t_pays VALUES ('NF','Ile Norfolk');
INSERT INTO ifacture.t_pays VALUES ('KY','Iles Cayman');
INSERT INTO ifacture.t_pays VALUES ('CK','Iles Cook');
INSERT INTO ifacture.t_pays VALUES ('CC','Iles des Cocos (Keeling)');
INSERT INTO ifacture.t_pays VALUES ('FK','Iles Falkland');
INSERT INTO ifacture.t_pays VALUES ('FO','Iles Féroé');
INSERT INTO ifacture.t_pays VALUES ('FJ','Iles Fidji');
INSERT INTO ifacture.t_pays VALUES ('GS','Iles Géorgie du Sud et Sandwich du Sud');
INSERT INTO ifacture.t_pays VALUES ('HM','Iles Heard et McDonald');
INSERT INTO ifacture.t_pays VALUES ('MH','Iles Marshall');
INSERT INTO ifacture.t_pays VALUES ('UM','Iles mineures éloignées des États-Unis');
INSERT INTO ifacture.t_pays VALUES ('PN','Iles Pitcairn');
INSERT INTO ifacture.t_pays VALUES ('SB','Iles Salomon');
INSERT INTO ifacture.t_pays VALUES ('SJ','Iles Svalbard et Jan Mayen');
INSERT INTO ifacture.t_pays VALUES ('TC','Iles Turks-et-Caicos');
INSERT INTO ifacture.t_pays VALUES ('VI','Iles Vierges américaines');
INSERT INTO ifacture.t_pays VALUES ('VG','Iles Vierges britanniques');
INSERT INTO ifacture.t_pays VALUES ('IN','Inde');
INSERT INTO ifacture.t_pays VALUES ('ID','Indonésie');
INSERT INTO ifacture.t_pays VALUES ('IR','Iran');
INSERT INTO ifacture.t_pays VALUES ('IQ','Iraq');
INSERT INTO ifacture.t_pays VALUES ('IE','Irlande');
INSERT INTO ifacture.t_pays VALUES ('IS','Islande');
INSERT INTO ifacture.t_pays VALUES ('IL','Israël');
INSERT INTO ifacture.t_pays VALUES ('IT','Italie');
INSERT INTO ifacture.t_pays VALUES ('JM','Jamaïque');
INSERT INTO ifacture.t_pays VALUES ('JP','Japon');
INSERT INTO ifacture.t_pays VALUES ('JO','Jordanie');
INSERT INTO ifacture.t_pays VALUES ('KZ','Kazakhstan');
INSERT INTO ifacture.t_pays VALUES ('KE','Kenya');
INSERT INTO ifacture.t_pays VALUES ('KG','Kirghizistan');
INSERT INTO ifacture.t_pays VALUES ('KI','Kiribati');
INSERT INTO ifacture.t_pays VALUES ('KW','Koweït');
INSERT INTO ifacture.t_pays VALUES ('LA','Laos');
INSERT INTO ifacture.t_pays VALUES ('LS','Lesotho');
INSERT INTO ifacture.t_pays VALUES ('LV','Lettonie');
INSERT INTO ifacture.t_pays VALUES ('LB','Liban');
INSERT INTO ifacture.t_pays VALUES ('LR','Liberia');
INSERT INTO ifacture.t_pays VALUES ('LY','Libye');
INSERT INTO ifacture.t_pays VALUES ('LI','Liechtenstein');
INSERT INTO ifacture.t_pays VALUES ('LT','Lituanie');
INSERT INTO ifacture.t_pays VALUES ('LU','Luxembourg');
INSERT INTO ifacture.t_pays VALUES ('MO','Macao');
INSERT INTO ifacture.t_pays VALUES ('MG','Madagascar');
INSERT INTO ifacture.t_pays VALUES ('MY','Malaisie');
INSERT INTO ifacture.t_pays VALUES ('MW','Malawi');
INSERT INTO ifacture.t_pays VALUES ('MV','Maldives');
INSERT INTO ifacture.t_pays VALUES ('ML','Mali');
INSERT INTO ifacture.t_pays VALUES ('MT','Malte');
INSERT INTO ifacture.t_pays VALUES ('MP','Mariannes du Nord');
INSERT INTO ifacture.t_pays VALUES ('MA','Maroc');
INSERT INTO ifacture.t_pays VALUES ('MQ','Martinique');
INSERT INTO ifacture.t_pays VALUES ('MU','Maurice');
INSERT INTO ifacture.t_pays VALUES ('MR','Mauritanie');
INSERT INTO ifacture.t_pays VALUES ('YT','Mayotte');
INSERT INTO ifacture.t_pays VALUES ('MX','Mexique');
INSERT INTO ifacture.t_pays VALUES ('FM','Micronésie');
INSERT INTO ifacture.t_pays VALUES ('MD','Moldavie');
INSERT INTO ifacture.t_pays VALUES ('MC','Monaco');
INSERT INTO ifacture.t_pays VALUES ('MN','Mongolie');
INSERT INTO ifacture.t_pays VALUES ('MS','Montserrat');
INSERT INTO ifacture.t_pays VALUES ('MZ','Mozambique');
INSERT INTO ifacture.t_pays VALUES ('NA','Namibie');
INSERT INTO ifacture.t_pays VALUES ('NR','Nauru');
INSERT INTO ifacture.t_pays VALUES ('NP','Népal');
INSERT INTO ifacture.t_pays VALUES ('NI','Nicaragua');
INSERT INTO ifacture.t_pays VALUES ('NE','Niger');
INSERT INTO ifacture.t_pays VALUES ('NG','Nigeria');
INSERT INTO ifacture.t_pays VALUES ('NU','Nioué');
INSERT INTO ifacture.t_pays VALUES ('NO','Norvège');
INSERT INTO ifacture.t_pays VALUES ('NC','Nouvelle-Calédonie');
INSERT INTO ifacture.t_pays VALUES ('NZ','Nouvelle-Zélande');
INSERT INTO ifacture.t_pays VALUES ('OM','Oman');
INSERT INTO ifacture.t_pays VALUES ('UG','Ouganda');
INSERT INTO ifacture.t_pays VALUES ('UZ','Ouzbékistan');
INSERT INTO ifacture.t_pays VALUES ('PK','Pakistan');
INSERT INTO ifacture.t_pays VALUES ('PS','Palestinien occupé, territoire');
INSERT INTO ifacture.t_pays VALUES ('PA','Panama');
INSERT INTO ifacture.t_pays VALUES ('PG','Papouasie-Nouvelle-Guinée');
INSERT INTO ifacture.t_pays VALUES ('PY','Paraguay');
INSERT INTO ifacture.t_pays VALUES ('NL','ifacture.t_pays-Bas');
INSERT INTO ifacture.t_pays VALUES ('PE','Pérou');
INSERT INTO ifacture.t_pays VALUES ('PH','Philippines');
INSERT INTO ifacture.t_pays VALUES ('PL','Pologne');
INSERT INTO ifacture.t_pays VALUES ('PF','Polynésie française');
INSERT INTO ifacture.t_pays VALUES ('PR','Porto Rico');
INSERT INTO ifacture.t_pays VALUES ('PT','Portugal');
INSERT INTO ifacture.t_pays VALUES ('QA','Qatar');
INSERT INTO ifacture.t_pays VALUES ('CF','République centrafricaine');
INSERT INTO ifacture.t_pays VALUES ('CD','République démocratique du Congo');
INSERT INTO ifacture.t_pays VALUES ('DO','République dominicaine');
INSERT INTO ifacture.t_pays VALUES ('CZ','République tchèque');
INSERT INTO ifacture.t_pays VALUES ('RE','Réunion');
INSERT INTO ifacture.t_pays VALUES ('RO','Roumanie');
INSERT INTO ifacture.t_pays VALUES ('GB','Royaume-Uni');
INSERT INTO ifacture.t_pays VALUES ('RU','Russie');
INSERT INTO ifacture.t_pays VALUES ('RW','Rwanda');
INSERT INTO ifacture.t_pays VALUES ('EH','Sahara occidental');
INSERT INTO ifacture.t_pays VALUES ('KN','Saint-Christophe-et-Niévès');
INSERT INTO ifacture.t_pays VALUES ('SH','Sainte-Hélène');
INSERT INTO ifacture.t_pays VALUES ('LC','Sainte-Lucie');
INSERT INTO ifacture.t_pays VALUES ('SM','Saint-Marin');
INSERT INTO ifacture.t_pays VALUES ('PM','Saint-Pierre-et-Miquelon');
INSERT INTO ifacture.t_pays VALUES ('VA','Saint-Siège');
INSERT INTO ifacture.t_pays VALUES ('VC','Saint-Vincent-et-les-Grenadines');
INSERT INTO ifacture.t_pays VALUES ('SV','Salvador');
INSERT INTO ifacture.t_pays VALUES ('WS','Samoa');
INSERT INTO ifacture.t_pays VALUES ('AS','Samoa américaines');
INSERT INTO ifacture.t_pays VALUES ('ST','Sao Tomé-et-Principe');
INSERT INTO ifacture.t_pays VALUES ('SN','Sénégal');
INSERT INTO ifacture.t_pays VALUES ('SC','Seychelles');
INSERT INTO ifacture.t_pays VALUES ('SL','Sierra Leone');
INSERT INTO ifacture.t_pays VALUES ('SG','Singapour');
INSERT INTO ifacture.t_pays VALUES ('SK','Slovaquie');
INSERT INTO ifacture.t_pays VALUES ('SI','Slovénie');
INSERT INTO ifacture.t_pays VALUES ('SO','Somalie');
INSERT INTO ifacture.t_pays VALUES ('SD','Soudan');
INSERT INTO ifacture.t_pays VALUES ('LK','Sri Lanka');
INSERT INTO ifacture.t_pays VALUES ('SE','Suède');
INSERT INTO ifacture.t_pays VALUES ('CH','Suisse');
INSERT INTO ifacture.t_pays VALUES ('SR','Suriname');
INSERT INTO ifacture.t_pays VALUES ('SZ','Swaziland');
INSERT INTO ifacture.t_pays VALUES ('SY','Syrie');
INSERT INTO ifacture.t_pays VALUES ('TJ','Tadjikistan');
INSERT INTO ifacture.t_pays VALUES ('TW','Taïwan');
INSERT INTO ifacture.t_pays VALUES ('TZ','Tanzanie');
INSERT INTO ifacture.t_pays VALUES ('TD','Tchad');
INSERT INTO ifacture.t_pays VALUES ('TF','Terres australes françaises');
INSERT INTO ifacture.t_pays VALUES ('IO','Territoire britannique de l''Océan Indien');
INSERT INTO ifacture.t_pays VALUES ('TH','Thaïlande');
INSERT INTO ifacture.t_pays VALUES ('TL','Timor Oriental');
INSERT INTO ifacture.t_pays VALUES ('TG','Togo');
INSERT INTO ifacture.t_pays VALUES ('TK','Tokélaou');
INSERT INTO ifacture.t_pays VALUES ('TO','Tonga');
INSERT INTO ifacture.t_pays VALUES ('TT','Trinité-et-Tobago');
INSERT INTO ifacture.t_pays VALUES ('TN','Tunisie');
INSERT INTO ifacture.t_pays VALUES ('TM','Turkménistan');
INSERT INTO ifacture.t_pays VALUES ('TR','Turquie');
INSERT INTO ifacture.t_pays VALUES ('TV','Tuvalu');
INSERT INTO ifacture.t_pays VALUES ('UA','Ukraine');
INSERT INTO ifacture.t_pays VALUES ('UY','Uruguay');
INSERT INTO ifacture.t_pays VALUES ('VU','Vanuatu');
INSERT INTO ifacture.t_pays VALUES ('VE','Venezuela');
INSERT INTO ifacture.t_pays VALUES ('VN','Viêt Nam');
INSERT INTO ifacture.t_pays VALUES ('WF','Wallis-et-Futuna');
INSERT INTO ifacture.t_pays VALUES ('YE','Yémen');
INSERT INTO ifacture.t_pays VALUES ('YU','Yougoslavie');
INSERT INTO ifacture.t_pays VALUES ('ZM','Zambie');
INSERT INTO ifacture.t_pays VALUES ('ZW','Zimbabwe');